
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Message` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Message
 * 
 */
export type MessageModel = runtime.Types.Result.DefaultSelection<Prisma.$MessagePayload>

export type AggregateMessage = {
  _count: MessageCountAggregateOutputType | null
  _avg: MessageAvgAggregateOutputType | null
  _sum: MessageSumAggregateOutputType | null
  _min: MessageMinAggregateOutputType | null
  _max: MessageMaxAggregateOutputType | null
}

export type MessageAvgAggregateOutputType = {
  mediaFileSize: number | null
  mediaDuration: number | null
  chatwootConversationId: number | null
  chatwootMessageId: number | null
  chatwootContactId: number | null
}

export type MessageSumAggregateOutputType = {
  mediaFileSize: number | null
  mediaDuration: number | null
  chatwootConversationId: number | null
  chatwootMessageId: number | null
  chatwootContactId: number | null
}

export type MessageMinAggregateOutputType = {
  id: string | null
  externalId: string | null
  direction: string | null
  type: string | null
  from: string | null
  to: string | null
  chatId: string | null
  content: string | null
  mediaUrl: string | null
  mediaMimeType: string | null
  mediaFileName: string | null
  mediaFileSize: number | null
  mediaDuration: number | null
  isGroup: boolean | null
  quotedMessageId: string | null
  timestamp: Date | null
  status: string | null
  error: string | null
  chatwootConversationId: number | null
  chatwootMessageId: number | null
  chatwootContactId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MessageMaxAggregateOutputType = {
  id: string | null
  externalId: string | null
  direction: string | null
  type: string | null
  from: string | null
  to: string | null
  chatId: string | null
  content: string | null
  mediaUrl: string | null
  mediaMimeType: string | null
  mediaFileName: string | null
  mediaFileSize: number | null
  mediaDuration: number | null
  isGroup: boolean | null
  quotedMessageId: string | null
  timestamp: Date | null
  status: string | null
  error: string | null
  chatwootConversationId: number | null
  chatwootMessageId: number | null
  chatwootContactId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MessageCountAggregateOutputType = {
  id: number
  externalId: number
  direction: number
  type: number
  from: number
  to: number
  chatId: number
  content: number
  mediaUrl: number
  mediaMimeType: number
  mediaFileName: number
  mediaFileSize: number
  mediaDuration: number
  isGroup: number
  quotedMessageId: number
  timestamp: number
  status: number
  error: number
  chatwootConversationId: number
  chatwootMessageId: number
  chatwootContactId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MessageAvgAggregateInputType = {
  mediaFileSize?: true
  mediaDuration?: true
  chatwootConversationId?: true
  chatwootMessageId?: true
  chatwootContactId?: true
}

export type MessageSumAggregateInputType = {
  mediaFileSize?: true
  mediaDuration?: true
  chatwootConversationId?: true
  chatwootMessageId?: true
  chatwootContactId?: true
}

export type MessageMinAggregateInputType = {
  id?: true
  externalId?: true
  direction?: true
  type?: true
  from?: true
  to?: true
  chatId?: true
  content?: true
  mediaUrl?: true
  mediaMimeType?: true
  mediaFileName?: true
  mediaFileSize?: true
  mediaDuration?: true
  isGroup?: true
  quotedMessageId?: true
  timestamp?: true
  status?: true
  error?: true
  chatwootConversationId?: true
  chatwootMessageId?: true
  chatwootContactId?: true
  createdAt?: true
  updatedAt?: true
}

export type MessageMaxAggregateInputType = {
  id?: true
  externalId?: true
  direction?: true
  type?: true
  from?: true
  to?: true
  chatId?: true
  content?: true
  mediaUrl?: true
  mediaMimeType?: true
  mediaFileName?: true
  mediaFileSize?: true
  mediaDuration?: true
  isGroup?: true
  quotedMessageId?: true
  timestamp?: true
  status?: true
  error?: true
  chatwootConversationId?: true
  chatwootMessageId?: true
  chatwootContactId?: true
  createdAt?: true
  updatedAt?: true
}

export type MessageCountAggregateInputType = {
  id?: true
  externalId?: true
  direction?: true
  type?: true
  from?: true
  to?: true
  chatId?: true
  content?: true
  mediaUrl?: true
  mediaMimeType?: true
  mediaFileName?: true
  mediaFileSize?: true
  mediaDuration?: true
  isGroup?: true
  quotedMessageId?: true
  timestamp?: true
  status?: true
  error?: true
  chatwootConversationId?: true
  chatwootMessageId?: true
  chatwootContactId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Message to aggregate.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Messages
  **/
  _count?: true | MessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MessageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MessageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessageMaxAggregateInputType
}

export type GetMessageAggregateType<T extends MessageAggregateArgs> = {
      [P in keyof T & keyof AggregateMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessage[P]>
    : Prisma.GetScalarType<T[P], AggregateMessage[P]>
}




export type MessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithAggregationInput | Prisma.MessageOrderByWithAggregationInput[]
  by: Prisma.MessageScalarFieldEnum[] | Prisma.MessageScalarFieldEnum
  having?: Prisma.MessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessageCountAggregateInputType | true
  _avg?: MessageAvgAggregateInputType
  _sum?: MessageSumAggregateInputType
  _min?: MessageMinAggregateInputType
  _max?: MessageMaxAggregateInputType
}

export type MessageGroupByOutputType = {
  id: string
  externalId: string
  direction: string
  type: string
  from: string
  to: string
  chatId: string
  content: string | null
  mediaUrl: string | null
  mediaMimeType: string | null
  mediaFileName: string | null
  mediaFileSize: number | null
  mediaDuration: number | null
  isGroup: boolean
  quotedMessageId: string | null
  timestamp: Date
  status: string
  error: string | null
  chatwootConversationId: number | null
  chatwootMessageId: number | null
  chatwootContactId: number | null
  createdAt: Date
  updatedAt: Date
  _count: MessageCountAggregateOutputType | null
  _avg: MessageAvgAggregateOutputType | null
  _sum: MessageSumAggregateOutputType | null
  _min: MessageMinAggregateOutputType | null
  _max: MessageMaxAggregateOutputType | null
}

export type GetMessageGroupByPayload<T extends MessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessageGroupByOutputType[P]>
      }
    >
  >



export type MessageWhereInput = {
  AND?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  OR?: Prisma.MessageWhereInput[]
  NOT?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  id?: Prisma.StringFilter<"Message"> | string
  externalId?: Prisma.StringFilter<"Message"> | string
  direction?: Prisma.StringFilter<"Message"> | string
  type?: Prisma.StringFilter<"Message"> | string
  from?: Prisma.StringFilter<"Message"> | string
  to?: Prisma.StringFilter<"Message"> | string
  chatId?: Prisma.StringFilter<"Message"> | string
  content?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaUrl?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaMimeType?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaFileName?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaFileSize?: Prisma.IntNullableFilter<"Message"> | number | null
  mediaDuration?: Prisma.IntNullableFilter<"Message"> | number | null
  isGroup?: Prisma.BoolFilter<"Message"> | boolean
  quotedMessageId?: Prisma.StringNullableFilter<"Message"> | string | null
  timestamp?: Prisma.DateTimeFilter<"Message"> | Date | string
  status?: Prisma.StringFilter<"Message"> | string
  error?: Prisma.StringNullableFilter<"Message"> | string | null
  chatwootConversationId?: Prisma.IntNullableFilter<"Message"> | number | null
  chatwootMessageId?: Prisma.IntNullableFilter<"Message"> | number | null
  chatwootContactId?: Prisma.IntNullableFilter<"Message"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Message"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Message"> | Date | string
}

export type MessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  type?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaMimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaFileName?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaFileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaDuration?: Prisma.SortOrderInput | Prisma.SortOrder
  isGroup?: Prisma.SortOrder
  quotedMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  externalId?: string
  AND?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  OR?: Prisma.MessageWhereInput[]
  NOT?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  direction?: Prisma.StringFilter<"Message"> | string
  type?: Prisma.StringFilter<"Message"> | string
  from?: Prisma.StringFilter<"Message"> | string
  to?: Prisma.StringFilter<"Message"> | string
  chatId?: Prisma.StringFilter<"Message"> | string
  content?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaUrl?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaMimeType?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaFileName?: Prisma.StringNullableFilter<"Message"> | string | null
  mediaFileSize?: Prisma.IntNullableFilter<"Message"> | number | null
  mediaDuration?: Prisma.IntNullableFilter<"Message"> | number | null
  isGroup?: Prisma.BoolFilter<"Message"> | boolean
  quotedMessageId?: Prisma.StringNullableFilter<"Message"> | string | null
  timestamp?: Prisma.DateTimeFilter<"Message"> | Date | string
  status?: Prisma.StringFilter<"Message"> | string
  error?: Prisma.StringNullableFilter<"Message"> | string | null
  chatwootConversationId?: Prisma.IntNullableFilter<"Message"> | number | null
  chatwootMessageId?: Prisma.IntNullableFilter<"Message"> | number | null
  chatwootContactId?: Prisma.IntNullableFilter<"Message"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Message"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Message"> | Date | string
}, "id" | "externalId">

export type MessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  type?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaMimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaFileName?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaFileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaDuration?: Prisma.SortOrderInput | Prisma.SortOrder
  isGroup?: Prisma.SortOrder
  quotedMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MessageCountOrderByAggregateInput
  _avg?: Prisma.MessageAvgOrderByAggregateInput
  _max?: Prisma.MessageMaxOrderByAggregateInput
  _min?: Prisma.MessageMinOrderByAggregateInput
  _sum?: Prisma.MessageSumOrderByAggregateInput
}

export type MessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessageScalarWhereWithAggregatesInput | Prisma.MessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessageScalarWhereWithAggregatesInput | Prisma.MessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Message"> | string
  externalId?: Prisma.StringWithAggregatesFilter<"Message"> | string
  direction?: Prisma.StringWithAggregatesFilter<"Message"> | string
  type?: Prisma.StringWithAggregatesFilter<"Message"> | string
  from?: Prisma.StringWithAggregatesFilter<"Message"> | string
  to?: Prisma.StringWithAggregatesFilter<"Message"> | string
  chatId?: Prisma.StringWithAggregatesFilter<"Message"> | string
  content?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  mediaUrl?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  mediaMimeType?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  mediaFileName?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  mediaFileSize?: Prisma.IntNullableWithAggregatesFilter<"Message"> | number | null
  mediaDuration?: Prisma.IntNullableWithAggregatesFilter<"Message"> | number | null
  isGroup?: Prisma.BoolWithAggregatesFilter<"Message"> | boolean
  quotedMessageId?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"Message"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"Message"> | string
  error?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  chatwootConversationId?: Prisma.IntNullableWithAggregatesFilter<"Message"> | number | null
  chatwootMessageId?: Prisma.IntNullableWithAggregatesFilter<"Message"> | number | null
  chatwootContactId?: Prisma.IntNullableWithAggregatesFilter<"Message"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Message"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Message"> | Date | string
}

export type MessageCreateInput = {
  id?: string
  externalId: string
  direction: string
  type: string
  from: string
  to: string
  chatId: string
  content?: string | null
  mediaUrl?: string | null
  mediaMimeType?: string | null
  mediaFileName?: string | null
  mediaFileSize?: number | null
  mediaDuration?: number | null
  isGroup?: boolean
  quotedMessageId?: string | null
  timestamp: Date | string
  status?: string
  error?: string | null
  chatwootConversationId?: number | null
  chatwootMessageId?: number | null
  chatwootContactId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MessageUncheckedCreateInput = {
  id?: string
  externalId: string
  direction: string
  type: string
  from: string
  to: string
  chatId: string
  content?: string | null
  mediaUrl?: string | null
  mediaMimeType?: string | null
  mediaFileName?: string | null
  mediaFileSize?: number | null
  mediaDuration?: number | null
  isGroup?: boolean
  quotedMessageId?: string | null
  timestamp: Date | string
  status?: string
  error?: string | null
  chatwootConversationId?: number | null
  chatwootMessageId?: number | null
  chatwootContactId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaDuration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean
  quotedMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chatwootConversationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootContactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaDuration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean
  quotedMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chatwootConversationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootContactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageCreateManyInput = {
  id?: string
  externalId: string
  direction: string
  type: string
  from: string
  to: string
  chatId: string
  content?: string | null
  mediaUrl?: string | null
  mediaMimeType?: string | null
  mediaFileName?: string | null
  mediaFileSize?: number | null
  mediaDuration?: number | null
  isGroup?: boolean
  quotedMessageId?: string | null
  timestamp: Date | string
  status?: string
  error?: string | null
  chatwootConversationId?: number | null
  chatwootMessageId?: number | null
  chatwootContactId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaDuration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean
  quotedMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chatwootConversationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootContactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaMimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaFileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mediaDuration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean
  quotedMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chatwootConversationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  chatwootContactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  type?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaMimeType?: Prisma.SortOrder
  mediaFileName?: Prisma.SortOrder
  mediaFileSize?: Prisma.SortOrder
  mediaDuration?: Prisma.SortOrder
  isGroup?: Prisma.SortOrder
  quotedMessageId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MessageAvgOrderByAggregateInput = {
  mediaFileSize?: Prisma.SortOrder
  mediaDuration?: Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrder
}

export type MessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  type?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaMimeType?: Prisma.SortOrder
  mediaFileName?: Prisma.SortOrder
  mediaFileSize?: Prisma.SortOrder
  mediaDuration?: Prisma.SortOrder
  isGroup?: Prisma.SortOrder
  quotedMessageId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  type?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaMimeType?: Prisma.SortOrder
  mediaFileName?: Prisma.SortOrder
  mediaFileSize?: Prisma.SortOrder
  mediaDuration?: Prisma.SortOrder
  isGroup?: Prisma.SortOrder
  quotedMessageId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MessageSumOrderByAggregateInput = {
  mediaFileSize?: Prisma.SortOrder
  mediaDuration?: Prisma.SortOrder
  chatwootConversationId?: Prisma.SortOrder
  chatwootMessageId?: Prisma.SortOrder
  chatwootContactId?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type MessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externalId?: boolean
  direction?: boolean
  type?: boolean
  from?: boolean
  to?: boolean
  chatId?: boolean
  content?: boolean
  mediaUrl?: boolean
  mediaMimeType?: boolean
  mediaFileName?: boolean
  mediaFileSize?: boolean
  mediaDuration?: boolean
  isGroup?: boolean
  quotedMessageId?: boolean
  timestamp?: boolean
  status?: boolean
  error?: boolean
  chatwootConversationId?: boolean
  chatwootMessageId?: boolean
  chatwootContactId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["message"]>

export type MessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externalId?: boolean
  direction?: boolean
  type?: boolean
  from?: boolean
  to?: boolean
  chatId?: boolean
  content?: boolean
  mediaUrl?: boolean
  mediaMimeType?: boolean
  mediaFileName?: boolean
  mediaFileSize?: boolean
  mediaDuration?: boolean
  isGroup?: boolean
  quotedMessageId?: boolean
  timestamp?: boolean
  status?: boolean
  error?: boolean
  chatwootConversationId?: boolean
  chatwootMessageId?: boolean
  chatwootContactId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["message"]>

export type MessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externalId?: boolean
  direction?: boolean
  type?: boolean
  from?: boolean
  to?: boolean
  chatId?: boolean
  content?: boolean
  mediaUrl?: boolean
  mediaMimeType?: boolean
  mediaFileName?: boolean
  mediaFileSize?: boolean
  mediaDuration?: boolean
  isGroup?: boolean
  quotedMessageId?: boolean
  timestamp?: boolean
  status?: boolean
  error?: boolean
  chatwootConversationId?: boolean
  chatwootMessageId?: boolean
  chatwootContactId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["message"]>

export type MessageSelectScalar = {
  id?: boolean
  externalId?: boolean
  direction?: boolean
  type?: boolean
  from?: boolean
  to?: boolean
  chatId?: boolean
  content?: boolean
  mediaUrl?: boolean
  mediaMimeType?: boolean
  mediaFileName?: boolean
  mediaFileSize?: boolean
  mediaDuration?: boolean
  isGroup?: boolean
  quotedMessageId?: boolean
  timestamp?: boolean
  status?: boolean
  error?: boolean
  chatwootConversationId?: boolean
  chatwootMessageId?: boolean
  chatwootContactId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "externalId" | "direction" | "type" | "from" | "to" | "chatId" | "content" | "mediaUrl" | "mediaMimeType" | "mediaFileName" | "mediaFileSize" | "mediaDuration" | "isGroup" | "quotedMessageId" | "timestamp" | "status" | "error" | "chatwootConversationId" | "chatwootMessageId" | "chatwootContactId" | "createdAt" | "updatedAt", ExtArgs["result"]["message"]>

export type $MessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Message"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    externalId: string
    direction: string
    type: string
    from: string
    to: string
    chatId: string
    content: string | null
    mediaUrl: string | null
    mediaMimeType: string | null
    mediaFileName: string | null
    mediaFileSize: number | null
    mediaDuration: number | null
    isGroup: boolean
    quotedMessageId: string | null
    timestamp: Date
    status: string
    error: string | null
    chatwootConversationId: number | null
    chatwootMessageId: number | null
    chatwootContactId: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["message"]>
  composites: {}
}

export type MessageGetPayload<S extends boolean | null | undefined | MessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessagePayload, S>

export type MessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessageCountAggregateInputType | true
  }

export interface MessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Message'], meta: { name: 'Message' } }
  /**
   * Find zero or one Message that matches the filter.
   * @param {MessageFindUniqueArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessageFindUniqueArgs>(args: Prisma.SelectSubset<T, MessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Message that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessageFindUniqueOrThrowArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Message that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindFirstArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessageFindFirstArgs>(args?: Prisma.SelectSubset<T, MessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Message that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindFirstOrThrowArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Messages
   * const messages = await prisma.message.findMany()
   * 
   * // Get first 10 Messages
   * const messages = await prisma.message.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messageWithIdOnly = await prisma.message.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MessageFindManyArgs>(args?: Prisma.SelectSubset<T, MessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Message.
   * @param {MessageCreateArgs} args - Arguments to create a Message.
   * @example
   * // Create one Message
   * const Message = await prisma.message.create({
   *   data: {
   *     // ... data to create a Message
   *   }
   * })
   * 
   */
  create<T extends MessageCreateArgs>(args: Prisma.SelectSubset<T, MessageCreateArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Messages.
   * @param {MessageCreateManyArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const message = await prisma.message.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessageCreateManyArgs>(args?: Prisma.SelectSubset<T, MessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Messages and returns the data saved in the database.
   * @param {MessageCreateManyAndReturnArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const message = await prisma.message.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Messages and only return the `id`
   * const messageWithIdOnly = await prisma.message.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Message.
   * @param {MessageDeleteArgs} args - Arguments to delete one Message.
   * @example
   * // Delete one Message
   * const Message = await prisma.message.delete({
   *   where: {
   *     // ... filter to delete one Message
   *   }
   * })
   * 
   */
  delete<T extends MessageDeleteArgs>(args: Prisma.SelectSubset<T, MessageDeleteArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Message.
   * @param {MessageUpdateArgs} args - Arguments to update one Message.
   * @example
   * // Update one Message
   * const message = await prisma.message.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessageUpdateArgs>(args: Prisma.SelectSubset<T, MessageUpdateArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Messages.
   * @param {MessageDeleteManyArgs} args - Arguments to filter Messages to delete.
   * @example
   * // Delete a few Messages
   * const { count } = await prisma.message.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Messages
   * const message = await prisma.message.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessageUpdateManyArgs>(args: Prisma.SelectSubset<T, MessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages and returns the data updated in the database.
   * @param {MessageUpdateManyAndReturnArgs} args - Arguments to update many Messages.
   * @example
   * // Update many Messages
   * const message = await prisma.message.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Messages and only return the `id`
   * const messageWithIdOnly = await prisma.message.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Message.
   * @param {MessageUpsertArgs} args - Arguments to update or create a Message.
   * @example
   * // Update or create a Message
   * const message = await prisma.message.upsert({
   *   create: {
   *     // ... data to create a Message
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Message we want to update
   *   }
   * })
   */
  upsert<T extends MessageUpsertArgs>(args: Prisma.SelectSubset<T, MessageUpsertArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageCountArgs} args - Arguments to filter Messages to count.
   * @example
   * // Count the number of Messages
   * const count = await prisma.message.count({
   *   where: {
   *     // ... the filter for the Messages we want to count
   *   }
   * })
  **/
  count<T extends MessageCountArgs>(
    args?: Prisma.Subset<T, MessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Message.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessageAggregateArgs>(args: Prisma.Subset<T, MessageAggregateArgs>): Prisma.PrismaPromise<GetMessageAggregateType<T>>

  /**
   * Group by Message.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessageGroupByArgs['orderBy'] }
      : { orderBy?: MessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Message model
 */
readonly fields: MessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Message.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Message model
 */
export interface MessageFieldRefs {
  readonly id: Prisma.FieldRef<"Message", 'String'>
  readonly externalId: Prisma.FieldRef<"Message", 'String'>
  readonly direction: Prisma.FieldRef<"Message", 'String'>
  readonly type: Prisma.FieldRef<"Message", 'String'>
  readonly from: Prisma.FieldRef<"Message", 'String'>
  readonly to: Prisma.FieldRef<"Message", 'String'>
  readonly chatId: Prisma.FieldRef<"Message", 'String'>
  readonly content: Prisma.FieldRef<"Message", 'String'>
  readonly mediaUrl: Prisma.FieldRef<"Message", 'String'>
  readonly mediaMimeType: Prisma.FieldRef<"Message", 'String'>
  readonly mediaFileName: Prisma.FieldRef<"Message", 'String'>
  readonly mediaFileSize: Prisma.FieldRef<"Message", 'Int'>
  readonly mediaDuration: Prisma.FieldRef<"Message", 'Int'>
  readonly isGroup: Prisma.FieldRef<"Message", 'Boolean'>
  readonly quotedMessageId: Prisma.FieldRef<"Message", 'String'>
  readonly timestamp: Prisma.FieldRef<"Message", 'DateTime'>
  readonly status: Prisma.FieldRef<"Message", 'String'>
  readonly error: Prisma.FieldRef<"Message", 'String'>
  readonly chatwootConversationId: Prisma.FieldRef<"Message", 'Int'>
  readonly chatwootMessageId: Prisma.FieldRef<"Message", 'Int'>
  readonly chatwootContactId: Prisma.FieldRef<"Message", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Message", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Message", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Message findUnique
 */
export type MessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message findUniqueOrThrow
 */
export type MessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message findFirst
 */
export type MessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message findFirstOrThrow
 */
export type MessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message findMany
 */
export type MessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message create
 */
export type MessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data needed to create a Message.
   */
  data: Prisma.XOR<Prisma.MessageCreateInput, Prisma.MessageUncheckedCreateInput>
}

/**
 * Message createMany
 */
export type MessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Messages.
   */
  data: Prisma.MessageCreateManyInput | Prisma.MessageCreateManyInput[]
}

/**
 * Message createManyAndReturn
 */
export type MessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data used to create many Messages.
   */
  data: Prisma.MessageCreateManyInput | Prisma.MessageCreateManyInput[]
}

/**
 * Message update
 */
export type MessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data needed to update a Message.
   */
  data: Prisma.XOR<Prisma.MessageUpdateInput, Prisma.MessageUncheckedUpdateInput>
  /**
   * Choose, which Message to update.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message updateMany
 */
export type MessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Messages.
   */
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyInput>
  /**
   * Filter which Messages to update
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to update.
   */
  limit?: number
}

/**
 * Message updateManyAndReturn
 */
export type MessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data used to update Messages.
   */
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyInput>
  /**
   * Filter which Messages to update
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to update.
   */
  limit?: number
}

/**
 * Message upsert
 */
export type MessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The filter to search for the Message to update in case it exists.
   */
  where: Prisma.MessageWhereUniqueInput
  /**
   * In case the Message found by the `where` argument doesn't exist, create a new Message with this data.
   */
  create: Prisma.XOR<Prisma.MessageCreateInput, Prisma.MessageUncheckedCreateInput>
  /**
   * In case the Message was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessageUpdateInput, Prisma.MessageUncheckedUpdateInput>
}

/**
 * Message delete
 */
export type MessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Filter which Message to delete.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message deleteMany
 */
export type MessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Messages to delete
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to delete.
   */
  limit?: number
}

/**
 * Message without action
 */
export type MessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
}
